### PR TITLE
feat: Combine configs using deepmerge

### LINKED ISSUE #21: usage of object.assign renders the utility of this library limited
currently, this library is using `Object.assign` as a method for overwriting config values, 

however with apps such as [`Settings`](https://github.com/probot/settings) the top level properties of the config are objects themselves, and thus any overwriting of those top-level objects does not propagate with `_extends` values due to `Object.assign` not doing any *deep* overrides.

thoughts on replacing object.assign with a *deep* alternative?

e.g. [`object-assign-deep`](https://www.npmjs.com/package/object-assign-deep)

### PR DESCRIPTION
**Pull request by jwsloan**
Prior to this change, all top-level keys of a config file would be
replaced entirely by the incoming config. For some apps, this may
be sufficient. However, some apps have complex settings, and the
extend feature is much more useful if you can be more granular about
what you are overriding.

With this change, you can keep as much or as little of the base config
as you'd like.

closes #21

### CODE REVIEW

**Comment by jwsloan** [comment]
As soon as this is complete, I'll be able to finish https://github.com/probot/settings/pull/105 . That will make the Settings app (especially Protected Branches) considerably more useful, and easier to use.

**Comment by travi** [comment]
this will be great! i've been hoping for similar for things even as simple as labels, so i could define a list at the org (`.github` repo) level and add repo specific labels rather than needing to include the full list and letting them get out of sync.

**Comment by gr2m** [comment]
deepmerge also merges arrays: https://runkit.com/gr2m/5beca2c2d45bc90012f63204. I don’t see a problem myself right now, but worth mentioning.

**Comment by jwsloan** [comment]
@gr2m, that is actually one of the features I'm counting on. It allows you to pass a function to use when merging arrays, and I'm going to use it for branch merging in the Protected Branches plugin for the Settings app.

**Comment by jwsloan** [comment]
I considered adding a few different merge functions to this repo that someone could choose to use. Maybe one that overwrites the existing array, one that merges elements based on their index, and one that takes a predicate function like `(TargetElement, SourceElement) -> Boolean`, and merges any for which the function returns true.

**Comment by ahmadnassri** [comment]
LOVELY! thank you!

**Comment by jwsloan** [comment]
Thanks for getting this up to date, @hiimbex. 

I'm curious if ya'll have considered switching to a `rebase` workflow instead of merging master into feature branches? In my experience, rebase along with only using fast-forward merges to master keeps master's history super clean.

**Comment by gr2m** [comment]
@jwsloan I agree with the rebase, I do it on all my repos. I use squash-merge, too. And I automate releases using semantic-release. We had that on Probot for a while but removed it after once a major version was released accidentally. I hope to get back to automating things, once semantic-release has a review step :)

**Pull request merged**
